Controllers/RegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AspDotNetMvcCodeFirstProject.Models;

namespace AspDotNetMvcCodeFirstProject.Controllers
{
    public class RegistrationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Registrations
        public ActionResult Index()
        {
            var registrations = db.Registrations.Include(r => r.Donor).Include(r => r.Patient);
            return View(registrations.ToList());
        }

        // GET: Registrations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // GET: Registrations/Create
        public ActionResult Create()
        {
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "DonorName");
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "PatientName");
            return View();
        }

        // POST: Registrations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RegistrationID,DonorID,Status,PatientID,IsActive")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Registrations.Add(registration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "DonorName", registration.DonorID);
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "PatientName", registration.PatientID);
            return View(registration);
        }

        // GET: Registrations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "DonorName", registration.DonorID);
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "PatientName", registration.PatientID);
            return View(registration);
        }

        // POST: Registrations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RegistrationID,DonorID,Status,PatientID,IsActive")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DonorID = new SelectList(db.Donors, "DonorID", "DonorName", registration.DonorID);
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "PatientName", registration.PatientID);
            return View(registration);
        }

        // GET: Registrations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // POST: Registrations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registration registration = db.Registrations.Find(id);
            db.Registrations.Remove(registration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BloodBank", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Donor Info", "Index", "Donor")</li>
                    <li>@Html.ActionLink("Patient Info", "Index", "Patient")</li>
                    <li>@Html.ActionLink("BloodGroup", "Index", "BloodGroup")</li>
                    <li>@Html.ActionLink("Registration Info", "Index", "Registrations")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_PatientDetail.cshtml
@model IList<AspDotNetMvcCodeFirstProject.Models.Patient>


<div class="table-responsive">
    <table class="table table-bordered table table-striped">
        <thead>
            <tr>
                <th>Patient Name</th>
                <th>Email Address</th>
                <th>Cell Phone</th>
                <th>Date Of Birth</th>
                <th>Gender</th>
                <th>Status</th>
                <th>Image</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CellPhoneNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.PatientImage)*@
                    <img src="@Url.Content(item.PatientImage)" height="80" width="80"/>
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Patient", new {id=item.PatientID})" class="editDialog">
                        <i class="fa fa-pencil-square-o"></i>Edit
                    </a>
                </td>
                <td>
                    @Ajax.ActionLink("Delete", "Delete", "Patient", new { @id = item.PatientID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "div-record" }, new { @class = "fa fa-trash-o" })
                </td>
            </tr>
            }
        </tbody>

    </table>

</div>

<script>
    $(document).ready(function () {

        $("#Add").click(function (event) {
            event.preventDefault();
            $.get(this.href, function (response) {
                $(".divForAdd").html(response);
            });

            $("#Add-Modal").modal({
                backdrop: "static",
            }, 'show');
        });

        $(".editDialog").click(function (event) {
            event.preventDefault();
            $.get(this.href, function (response) {
                $(".divForUpdate").html(response);
            });

            $("#Edit-Modal").modal({
                backdrop: "static",
            }, 'show');
        })
    })
</script>